---
- name: Base packages install
  yum: name={{ item }} state=present
  with_items:
    - bc
    - fio
    - rsync

- name: Copy the disk pressure test related scripts and config file
  template: src=pressure_test_all.sh dest=/tmp/ mode=755

- name: Del a disk pressure test profile
  file: path=/tmp/diskconfig state=absent

- name: Create a disk pressure test profile
  file: path=/tmp/diskconfig state=touch

- name: Insert the host list information
  lineinfile: dest=/tmp/diskconfig line={{ item }}
  with_items:
    - '{{ disk_name_list }}'

- name: Run disk pressure test scripts
  shell: '{{ item }}'
  with_items:
    - 'sh /tmp/pressure_test_all.sh disk_pressure_test'
#    - 'sleep {{ disk_test_time }}'
#    - 'sleep 60'

#- name: Run disk pressure test scripts data
#  shell: sh /tmp/pressure_test_all.sh disk_pressure_test_data

#- name: Create a disk pressure data mulu
#  file: path=/tmp/disk_pressure_data state=directory
#  delegate_to: 127.0.0.1
#  run_once: true

#- name: Sync disk pressure data
#  synchronize: mode=pull src=/tmp/{{ ansible_fqdn }}_disk.tar.gz dest=/tmp/disk_pressure_data archive=yes checksum=yes

#- name: clear disk pressure test related file
#  file: path={{ item }} state=absent
#  with_items:
#    - '/tmp/diskconfig'
#    - '/tmp/pressure_test_all.sh'
#    - '/tmp/{{ ansible_fqdn }}_disk.tar.gz'
